language: ruby

rvm: 2.4.1

matrix:
  include:
    - os: linux
      env: CXX=clang++ CC=clang
    - os: osx

addons:
  apt:
    packages:
      - squashfs-tools
      - texinfo

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install squashfs; fi

before_script:
  - mksquashfs -version
  - ruby --version

script:
  - rake build
