language: ruby

rvm: 2.4.1

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - squashfs-tools
      - texinfo

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install squashfs; fi

before_script:
  - mksquashfs -version
  - ruby --version

script:
  - rake build
