language: ruby

rvm: 2.4.1

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - squashfs-tools
      - texinfo

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install squashfs; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++" CC="clang"; fi

before_script:
  - mksquashfs -version
  - ruby --version

script:
  - rake build
